// Auto-generated by scripts/generate-gallery-data.mjs
// Do not edit manually. Add videos to public/videos/gallery/ and re-run build.

export interface GalleryItem {
  id: string;
  type: "image" | "video";
  src: string;
  poster?: string;
  alt: string;
}

export const galleryItems: GalleryItem[] = [
  {
    "id": "img-1",
    "type": "image",
    "src": "/images/gallery-1.webp",
    "alt": "Room with big bed in peach color"
  },
  {
    "id": "img-2",
    "type": "image",
    "src": "/images/gallery-2.webp",
    "alt": "Top terrace view with blue glass"
  },
  {
    "id": "img-3",
    "type": "image",
    "src": "/images/gallery-3.webp",
    "alt": "Living room with white table and TV"
  },
  {
    "id": "img-4",
    "type": "image",
    "src": "/images/gallery-4.webp",
    "alt": "Living room with peach chairs"
  },
  {
    "id": "img-5",
    "type": "image",
    "src": "/images/gallery-5.webp",
    "alt": "Living room with brown settings"
  },
  {
    "id": "img-6",
    "type": "image",
    "src": "/images/gallery-6.webp",
    "alt": "Living room with brown settings and TV"
  },
  {
    "id": "img-7",
    "type": "image",
    "src": "/images/gallery-7.webp",
    "alt": "Living room with brown settings and TV left side view"
  },
  {
    "id": "img-8",
    "type": "image",
    "src": "/images/gallery-8.webp",
    "alt": "Living room with bright lights"
  },
  {
    "id": "img-9",
    "type": "image",
    "src": "/images/gallery-9.webp",
    "alt": "Living room with brown curtains"
  },
  {
    "id": "img-10",
    "type": "image",
    "src": "/images/gallery-10.webp",
    "alt": "Apartment interior view"
  },
  {
    "id": "img-11",
    "type": "image",
    "src": "/images/gallery-11.webp",
    "alt": "Apartment living space"
  },
  {
    "id": "img-12",
    "type": "image",
    "src": "/images/gallery-12.webp",
    "alt": "Modern apartment design"
  },
  {
    "id": "img-13",
    "type": "image",
    "src": "/images/gallery-13.webp",
    "alt": "Apartment room interior"
  },
  {
    "id": "img-14",
    "type": "image",
    "src": "/images/gallery-14.webp",
    "alt": "Luxury apartment feature"
  },
  {
    "id": "img-15",
    "type": "image",
    "src": "/images/gallery-15.webp",
    "alt": "Apartment ambiance"
  },
  {
    "id": "img-16",
    "type": "image",
    "src": "/images/gallery-16.webp",
    "alt": "Apartment detail view"
  },
  {
    "id": "img-17",
    "type": "image",
    "src": "/images/gallery-17.webp",
    "alt": "Apartment living area"
  },
  {
    "id": "img-18",
    "type": "image",
    "src": "/images/gallery-18.webp",
    "alt": "Apartment interior showcase"
  },
  {
    "id": "vid-1",
    "type": "video",
    "src": "/videos/gallery/IMG_7487.MOV",
    "alt": "Video IMG_7487"
  },
  {
    "id": "vid-2",
    "type": "video",
    "src": "/videos/gallery/IMG_7489.MOV",
    "alt": "Video IMG_7489"
  },
  {
    "id": "vid-3",
    "type": "video",
    "src": "/videos/gallery/IMG_7501.MOV",
    "alt": "Video IMG_7501"
  },
  {
    "id": "vid-4",
    "type": "video",
    "src": "/videos/gallery/IMG_7502.MOV",
    "alt": "Video IMG_7502"
  },
  {
    "id": "vid-5",
    "type": "video",
    "src": "/videos/gallery/IMG_7503.MOV",
    "alt": "Video IMG_7503"
  },
  {
    "id": "vid-6",
    "type": "video",
    "src": "/videos/gallery/IMG_7506.MOV",
    "alt": "Video IMG_7506"
  },
  {
    "id": "vid-7",
    "type": "video",
    "src": "/videos/gallery/IMG_7507.MOV",
    "alt": "Video IMG_7507"
  },
  {
    "id": "vid-8",
    "type": "video",
    "src": "/videos/gallery/IMG_7510.MOV",
    "alt": "Video IMG_7510"
  },
  {
    "id": "vid-9",
    "type": "video",
    "src": "/videos/gallery/IMG_7513.MOV",
    "alt": "Video IMG_7513"
  },
  {
    "id": "vid-10",
    "type": "video",
    "src": "/videos/gallery/IMG_7514.MOV",
    "alt": "Video IMG_7514"
  },
  {
    "id": "vid-11",
    "type": "video",
    "src": "/videos/gallery/IMG_7547.MOV",
    "alt": "Video IMG_7547"
  }
];
